# Generated by Django 3.0.8 on 2020-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200922_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
