# Generated by Django 3.0.8 on 2020-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200922_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
        migrations.AddField(
            model_name='seller',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
