# Generated by Django 3.0.8 on 2020-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20200922_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.IntegerField(default='1'),
        ),
    ]
