# Generated by Django 3.0.8 on 2020-09-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20200922_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
