# Generated by Django 3.0.8 on 2020-09-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20200922_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='contact',
        ),
    ]
