# Generated by Django 3.0.8 on 2020-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_seller_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
