# Generated by Django 3.0.8 on 2020-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
