# Generated by Django 3.0.8 on 2020-08-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Phone',
            new_name='phone',
        ),
    ]
