# Generated by Django 3.0.8 on 2020-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_forum_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(blank=True, default='anonymous', max_length=200),
        ),
    ]
