# Generated by Django 3.0.8 on 2020-09-28 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20200928_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='forum',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
