# Generated by Django 3.0.8 on 2020-09-28 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_auto_20200928_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(blank=True, default='', max_length=1000)),
                ('username', models.CharField(default='', max_length=30)),
                ('discuss_username', models.CharField(default='', max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
            ],
        ),
    ]
