# Generated by Django 3.0.8 on 2020-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='discuss_username',
        ),
        migrations.AddField(
            model_name='reply',
            name='discuss_userid',
            field=models.IntegerField(default=0),
        ),
    ]
