# Generated by Django 3.0.8 on 2020-07-20 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200720_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
