# Generated by Django 3.0.8 on 2020-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.IntegerField(default=0),
        ),
    ]
