# Generated by Django 3.0.8 on 2020-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='processing', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(default='cash on delivery', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=255),
        ),
    ]
