# Generated by Django 3.0.8 on 2020-09-28 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200909_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('product_id', models.IntegerField()),
                ('review', models.CharField(max_length=2038)),
            ],
        ),
    ]
