# Generated by Django 3.0.8 on 2020-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201003_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='healthbenifits',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
