# Generated by Django 3.0.8 on 2020-07-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
